### PR TITLE
Create corpus1.txt

### PR DESCRIPTION
**Pull request by NaravasMeksem**

### CODE REVIEW

**Review by aksil1980 — COMMENTED** [review]
Afud i garrez-en à Dda Belqasem.
Ssarameɣ ad d-fkeɣ afud ula s tira, macci kan s umeslay aked ttmesliwt.
Ar tufat

**Comment by MohammedBelkacem** [comment]
Azul ay Aksil @aksil1980 
Tanemmirt-ik. Afus meqqren i neḥwaǧ d win n tira n tefyar, akked taɣect.
Ma yella wayen tesɛiḍ, azen-it-id dagi di Github.

**Comment by MohammedBelkacem** [comment]
Tanemmirt-ik s waṭaṣ. Tzmreḍ ad d-iniḍ isem-ik akken yekkmel, anisa-k d wacu i t-xeddmeḍ?

**Comment by MohammedBelkacem** [comment]
Tanemmirt-ik s waṭaṣ. Tzmreḍ ad d-iniḍ isem-ik akken yekkmel, anisa-k d wacu i t-xeddmeḍ?

**Comment by MohammedBelkacem** [comment]
Waɛɛɛɛɛɛɛɛɛɛɛɛɛ, ziɣ d Meksem :+1:  hihi

**Pull request merged**
